/* Creating a playoff bracket, take the top 3 teams from each division, sorted by average points per games then lowest PIM. To qualify, more than 10 games must have
been played. 1st overall team gets a bye  Determine games based off of rankings  */

--SELECT *, CAST(PTS as FLOAT)/GP AS AVG_PTS FROM chfteams 
--WHERE (DIV_RK LIKE 1 OR DIV_RK LIKE 2 OR DIV_RK LIKE 3) and GP >10
--ORDER BY AVG_PTS DESC, PIM DESC


--SELECT *, CAST(PTS as FLOAT)/GP AS AVG_PTS FROM chfteams 
--WHERE (DIV_RK LIKE 1 OR DIV_RK LIKE 2 OR DIV_RK LIKE 3) and GP >10
--ORDER BY AVG_PTS DESC, PIM DESC
--OFFSET 1 ROW FETCH NEXT 10 ROWS ONLY 


--SELECT *, CAST(PTS as FLOAT)/GP AS AVG_PTS FROM chfteams 
--WHERE (DIV_RK LIKE 1 OR DIV_RK LIKE 2 OR DIV_RK LIKE 3) and GP >10
--ORDER BY AVG_PTS DESC, PIM 
--OFFSET 11 ROWS FETCH NEXT 10 ROWS ONLY 


--SELECT *, CAST(PTS as FLOAT)/GP AS AVG_PTS INTO TOPSEEDS FROM chfteams 
--WHERE (DIV_RK LIKE 1 OR DIV_RK LIKE 2 OR DIV_RK LIKE 3) and GP >10
--ORDER BY AVG_PTS DESC, PIM DESC
--OFFSET 1 ROW FETCH NEXT 10 ROWS ONLY 

--SELECT *, CAST(PTS as FLOAT)/GP AS AVG_PTS INTO LOWSEEDS FROM chfteams 
--WHERE (DIV_RK LIKE 1 OR DIV_RK LIKE 2 OR DIV_RK LIKE 3) and GP >10
--ORDER BY AVG_PTS DESC, PIM 
--OFFSET 11 ROWS FETCH NEXT 10 ROWS ONLY 


--ALTER TABLE TOPSEEDS 
--ADD GAME INT IDENTITY(1,1) PRIMARY KEY 

--ALTER TABLE LOWSEEDS 
--ADD GAME INT IDENTITY(10,-1) PRIMARY KEY 



SELECT * FROM TOPSEEDS

SELECT * FROM LOWSEEDS
