--testing theory if players with more points have more penalties. look at the top fifty players and compare them to 200-250


--SELECT TOP 50 *, CAST(PTS AS FLOAT)/GP AS AVG_PTS, CAST(PIM AS FLOAT)/GP AS AVG_PIM INTO top50 FROM chfplayers
--ORDER BY AVG_PTS DESC

--SELECT *, CAST(PTS AS FLOAT)/GP AS AVG_PTS, CAST(PIM AS FLOAT)/GP AS AVG_PIM INTO TWOHUNDREAD FROM chfplayers
--ORDER BY AVG_PTS DESC
--OFFSET 200 ROWS FETCH NEXT 50 ROWS ONLY 

SELECT SUM(AVG_PTS) AS SUM_AVG_PTS, SUM(AVG_PIM) AS SUM_AVG_PIM FROM top50
SELECT SUM(AVG_PTS) AS SUM_AVG_PTS, SUM(AVG_PIM) AS SUM_AVG_PIM FROM TWOHUNDREAD