--compare players with the first name michael and james. compare gp, pts and pims

SELECT Player, AVG(CAST(GP AS FLOAT)) AS AVG_GP,AVG(CAST(PTS AS FLOAT)) AS AVG_PTS, AVG(CAST(PIM AS FLOAT)) AS AVG_PIM INTO JAMES FROM chfplayers
WHERE  Player LIKE '%James%'
GROUP BY Player WITH ROLLUP

SELECT Player, AVG(CAST(GP AS FLOAT)) AS AVG_GP,AVG(CAST(PTS AS FLOAT)) AS AVG_PTS, AVG(CAST(PIM AS FLOAT)) AS AVG_PIM INTO MICHAEL FROM chfplayers
WHERE Player LIKE '%Michael%'
GROUP BY PLAYER WITH ROLLUP

SELECT * FROM JAMES
SELECT * FROM MICHAEL